plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"
}
rootProject.name = "playgroundKotlin"
include("lesClasses")
include("heritahe")
include("classesAbstraites")
include("desClassesDansDesClasses")
include("lesEnumerations")
include("lesTableaux")
include("ClassesParticuliere")
include("objetcSingleton")
include("lesLambda")
include("lesVariables")
include("lesStructuresDeControle")
include("lesFonction")
include("lesInterface")
include("lesFonctionsOrdreSuperieur")
include("nullabilite")
include("lesException")
include("lesCollections")
include("lesCoroutines")
include("lesTypeNullable")
include("fonctionDePorte")
include("LireEtEcrire")
include("lesFonctionsDePortees")
include("lesListess")
include("Heritage")
include("LaGenerique")
include("initialiserLesAtributsAutrement")
